### ISSUE TITLE
hPSMC: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by cnxiaobo94** [jacahill/hPSMC#8]
hi, I encountered a problem when doing hPSMC according to the tutorial. When I ran "psmcfa_from_2_fastas.py", the system reported the following error. Could you please help me find out the reason?
=================================
(bio2) [cug2202010039@m1001 hpsmc]$ python ../../hPSMC-master/psmcfa_from_2_fastas.py -b10 -m5 AS_N3_autosome.fa EU_Smoose_autosome.fa > AS_EU_hPSMC.psmcfa
  File "../../hPSMC-master/psmcfa_from_2_fastas.py", line 114
    elif indA=="G":
       ^
SyntaxError: invalid syntax

**Comment by cnxiaobo94** [comment]
I have tried both python2 and python3, but it did not work.

**Comment by aersoares81** [comment]
It's an indentation problem, and also there's another small problem if you use Python 3. I've fixed them and submitted a pull request.

**Comment by akfraik** [comment]
Hi there- I am also still receiving this error. Could you please help me understand why this is still happening? I cloned my repository in the last two weeks.

python ${hPSMC}/psmcfa_from_2_fastas.py -b10 -m5 ${OUTDIR}/CCT_Hap1_25.fa ${OUTDIR}/WCT_25.fa > ${OUTDIR}/WCT_CCT_25
  File "/../../hPSMC/psmcfa_from_2_fastas.py", line 114
    elif indA=="G":
       ^

Also, would you happen to have some example or test input/output to make sure it's working as it should? I think it would help me with some troubleshooting. Thanks.
